{{- if .Values.memcached.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fusionpbx.fullname" . }}-memcached
  labels:
    {{- include "fusionpbx.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
spec:
  replicas: {{ .Values.memcached.replicaCount }}
  selector:
    matchLabels:
      {{- include "fusionpbx.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: memcached
  template:
    metadata:
      labels:
        {{- include "fusionpbx.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: memcached
    spec:
      containers:
        - name: memcached
          image: "{{ .Values.memcached.image.repository }}:{{ .Values.memcached.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - memcached
            - -m 64
            - -c 1024
            - -t 4
          ports:
            - name: memcached
              containerPort: 11211
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fusionpbx.fullname" . }}-memcached
  labels:
    {{- include "fusionpbx.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
spec:
  type: ClusterIP
  ports:
    - port: 11211
      targetPort: memcached
      protocol: TCP
      name: memcached
  selector:
    {{- include "fusionpbx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
{{- end }}
