{{- if not .Values.postgresql.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fusionpbx.fullname" . }}-postgresql-credentials
  labels:
    {{- include "fusionpbx.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ include "fusionpbx.postgresql.host" . | b64enc | quote }}
  port: {{ include "fusionpbx.postgresql.port" . | b64enc | quote }}
  username: {{ include "fusionpbx.postgresql.user" . | b64enc | quote }}
  password: {{ include "fusionpbx.postgresql.password" . | b64enc | quote }}
  database: {{ include "fusionpbx.postgresql.database" . | b64enc | quote }}
{{- end }}
